# Generated by Django 4.2.2 on 2023-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_remove_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
