# Generated by Django 4.2.2 on 2023-07-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_recipe_dish_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='meal_plan',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recipe',
            field=models.ForeignKey(blank=True, default=40, on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe'),
        ),
    ]
