# Generated by Django 4.2.2 on 2023-07-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_calendarevent_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageURL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
