# Generated by Django 4.2.2 on 2023-07-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_recipe_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='imageURL',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
