# Generated by Django 4.2.2 on 2023-07-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0012_remove_calendarevent_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
