# Generated by Django 4.2.2 on 2023-07-13 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0013_mealplan_calendarevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='name',
        ),
    ]
