# Generated by Django 4.2.2 on 2023-07-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0014_remove_mealplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='title',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
