# Generated by Django 4.2.2 on 2023-07-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0016_remove_recipe_nutrition_recipe_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='calories',
        ),
    ]
