# Generated by Django 4.2.2 on 2023-07-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_remove_calendarevent_meal_plan_calendarevent_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='title',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe'),
        ),
    ]
