# Generated by Django 4.2.2 on 2023-07-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_delete_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
