# Generated by Django 4.2.2 on 2023-07-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0014_rename_end_calendarevent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe'),
        ),
    ]
